### PR TITLE
Updated looking for TaurusGui in utils.

### PR DESCRIPTION
**Pull request by LJBD**
I think that isinstance is a more "pythonic" way of determining an object's type. Moreover, it allows to subclass TaurusGui in case it is needed (and that's what I'm doing, too).

Are there any disadvantages which I'm not aware of?

### CODE REVIEW

**Comment by sergirubio** [comment]
Thanks! That workaround instead of isinstance was needed for a particular version of TaurusGUI that messed up with isinstance. 

I just have tested your branch with latest taurus 3* and the workaround is not needed anymore, so I merge your request.

**Comment by LJBD** [comment]
Okay, great!
By the way, are you planning to switch to Taurus 4 anytime soon?

**Comment by sergirubio** [comment]
Well, I can't do the "switch" directly because at ALBA we'll be still using Taurus 3 in most systems for at least a year. But, I can provide a compatibility layer to enable Vacca to run on both Taurus releases. 

I just created the taurus4 branch. If you want to contribute, just creating issues with the problems/exceptions you encounter would already help me to progress with it.

**Comment by sergirubio** [comment]
In spring 2017 we have to deploy a taurus4/tango9 system, so the switch 
will be done in the next months

How is it going with vacca, have you done any further test? Did you 
manage to run the elinac simulation?

**Comment by LJBD** [comment]
No, unfortunately I was busy with other things. I'll probably have time to dig into VACCA in the first week of  January.
Anyway, it's good to hear that there is a plan of switching to Taurus 4. I'll try to at least hint on the issues with it.

**Pull request merged**
